project:
  type: website
  output-dir: _site

website:
  title: "Assignment 1"
  subtitle: "Statistical Computing"
  author: "Euan Swart (SWREUA001)"

format:
  html:
    theme:
      - cosmo
      - custom.scss
    toc: true
    toc-depth: 3
    number-sections: true
    df-print: paged
    code-fold: false
    code-tools: true
    smooth-scroll: true
